apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wk8g46b45-java-springboot
  janus-idp.io/tekton: wk8g46b45-java-springboot
  backstage.io/kubernetes-id: wk8g46b45-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wk8g46b45-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
